use clap::Parser;
use std::path::PathBuf;

#[derive(Parser)]
#[command(
    name = "claude-pricing",
    about = "A CLI application generated by rust-scaffold",
    version = env!("GIT_DESCRIBE"),
)]
pub struct Cli {
    /// Path to config file
    #[arg(short, long, help = "Path to config file")]
    pub config: Option<PathBuf>,

    /// Enable verbose output
    #[arg(short, long, help = "Enable verbose output")]
    pub verbose: bool,
}
